import { BackgroundBeams } from '@/components/ui/background-beams'
import './globals.css'
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body >{children}<BackgroundBeams className='z-0 bg-neutral-950'/></body>
      
    </html>
  )
}
